apiVersion: v1
kind: Service
metadata:
  name: reactive-resume
  labels:
    app.kubernetes.io/name: reactive-resume
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.31
  selector:
    app.kubernetes.io/name: reactive-resume
  ports:
  - name: http
    port: 80
    targetPort: 3000
