apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-resume
      app.kubernetes.io/name: reactive-resume
  template:
    metadata:
      labels:
        app: reactive-resume
        app.kubernetes.io/name: reactive-resume
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-home-assistant: "secret/data/minio"
        vault.hashicorp.com/agent-inject-template-storage: |
          {{ with secret "secret/data/minio" }}
          export STORAGE_ACCESS_KEY="{{ .Data.data.MINIO_ROOT_USER }}"
          export STORAGE_SECRET_KEY="{{ .Data.data.MINIO_ROOT_PASSWORD }}"
          {{ end }}
    spec:
      containers:
      - name: reactive-resume
        image: ghcr.io/amruthpillai/reactive-resume
        command: ["sh", "-c"]
        args:
          - |
            . /vault/secrets/storage && \
            dumb-init pnpm run start
        envFrom:
        - configMapRef:
            name: reactive-resume-config
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 15
          failureThreshold: 3
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
