apiVersion: v1
kind: Service
metadata:
  name: navidrome-lb
  labels:
    app.kubernetes.io/name: navidrome
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.26
  selector:
    app.kubernetes.io/name: navidrome
  ports:
  - name: http
    port: 80
    targetPort: 4533
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/name: navidrome
    type: LoadBalancer
spec:
  selector:
    app.kubernetes.io/name: navidrome
  ports:
  - name: http
    port: 4533
    targetPort: 4533
