apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infisical-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical-postgresql
      app.kubernetes.io/name: infisical-postgresql
  serviceName: infisical-postgresql
  template:
    metadata:
      labels:
        app: infisical-postgresql
        app.kubernetes.io/name: infisical-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: infisical
        - name: POSTGRES_PASSWORD
          value: infisical
        - name: POSTGRES_DB
          value: infisical
        - name: PGDATA
          value: /mnt/infisical-postgresql
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
        livenessProbe:
          exec:
            command: [ "pg_isready", "-U", "infisical" ]
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command: [ "pg_isready", "-U", "infisical" ]
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        volumeMounts:
        - name: infisical-postgres
          mountPath: /mnt/infisical-postgresql
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: infisical-postgres
        persistentVolumeClaim:
          claimName: infisical-postgres-pvc
