apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/instance: infisical-selfhosted

spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical
      app.kubernetes.io/name: infisical
  template:
    metadata:
      labels:
        app: infisical
        app.kubernetes.io/name: infisical
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-smtp: "secret/data/smtp"
        vault.hashicorp.com/secret-volume-path: "/etc/infisical"
        vault.hashicorp.com/agent-inject-template-infisical.rb: |
          {{ with secret "secret/data/smtp" -}}
          # Variables de SMTP (Nota: estas pueden requerir un manejo diferente en Ruby si no son parte de infisical_core)
          infisical_core['SMTP_HOST'] = '{{ .Data.data.HOST }}'
          infisical_core['SMTP_PORT'] = '{{ .Data.data.PORT }}'
          infisical_core['SMTP_USERNAME'] = '{{ .Data.data.USER }}'
          infisical_core['SMTP_PASSWORD'] = '{{ .Data.data.PASSWORD }}'
          {{ end }}
    spec:
      containers:
      - name: infisical
        image: infisical/infisical:latest
        env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: infisical
              key: ENCRYPTION_KEY
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: infisical
              key: AUTH_SECRET
        - name: DB_CONNECTION_URI
          value: "postgresql://infisical:infisical@infisical-postgresql:5432/infisical"
        - name: REDIS_URL
          value: "redis://infisical-redis:6379"
        - name: SITE_URL
          value: "http://infisical.local"
        - name: AUTH_ENABLED
          value: "true"
        - name: EMAIL_SERVICE
          value: "nodemailer"
        - name: SMTP_IGNORE_TLS
          value: "true"
        - name: SMTP_REQUIRE_TLS
          value: "false"
        - name: SMTP_FROM_ADDRESS
          value: "infisical@citocafecito.work"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: 5m
        volumeMounts:
        - name: infisical-data
          mountPath: /mnt/infisical
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: infisical-data
        emptyDir: {}
