
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: actions
spec:
  selector:
    matchLabels:
      app: k8s-runners
      app.kubernetes.io/name: k8s-runners
  template:
    metadata:
      labels:
        app: k8s-runners
        app.kubernetes.io/name: k8s-runners
    spec:
      dockerEnabled: false
      organization: citocafecito-homelab
      serviceAccountName: github-runner
      labels: []
      env: []