apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: home.citocafecito.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubetail-dashboard
            port:
              number: 8080
  - host: kite.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kite
            port:
              number: 8080
  - host: music-assistant.citocafecito.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: music-assistant
            port:
              number: 8095