apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  labels:
    app: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
      app.kubernetes.io/name: chrome
  template:
    metadata:
      labels:
        app: chrome
        app.kubernetes.io/name: chrome
    spec:
      containers:
        - name: chrome
          image: ghcr.io/browserless/chromium:v2.18.0
          env:
          - name: TIMEOUT
            value: "10000"
          - name: CONCURRENT
            value: "3"
          - name: PREBOOT_CHROME
            value: "true"
          - name: "CHROME_FLAGS"
            value: "--disable-gpu --disable-dev-shm-usage --no-sandbox --single-process"
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: chrome-secret
                key: CHROME_TOKEN
          - name: EXIT_ON_HEALTH_FAILURE
            value: "true"
          - name: PRE_REQUEST_HEALTH_CHECK
            value: "true"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "300m"
              memory: "1.5Gi"
          # Din't work - I will check it later
          # livenessProbe:
          #   httpGet:
          #     path: /pressure
          #     port: 3000
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /pressure
          #     port: 3000
          #   initialDelaySeconds: 15
          #   periodSeconds: 15
          #   successThreshold: 1