apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Not enough cpu available
# - mydrive
# - infisical
# - reactive-resume
- minio

# Work in progress. Stoped due no enough hardware
# - next-cloud

namespace: storage
