apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- minio
- infisical
- reactive-resume
# Not enough cpu available
# - mydrive
# Work in progress
# - next-cloud

namespace: storage
