apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nextcloud
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        name: nextcloud
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        env:
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: admin
        - name: APACHE_SERVER_NAME
          value: nextcloud.citocafecito.work
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: nextcloud
        - name: POSTGRES_HOST
          value: nextcloud-postgresql.storage.svc.cluster.local
        - name: NEXTCLOUD_OBJECTSTORE_CLASS
          value: OC\Files\ObjectStore\S3
        - name: NEXTCLOUD_OBJECTSTORE_BUCKET
          value: nextcloud
        - name: NEXTCLOUD_OBJECTSTORE_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: NEXTCLOUD_OBJECTSTORE_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
        - name: NEXTCLOUD_OBJECTSTORE_HOST
          value: minio.default.svc.cluster.local
        - name: NEXTCLOUD_OBJECTSTORE_PORT
          value: "9000"
        - name: NEXTCLOUD_OBJECTSTORE_USE_SSL
          value: "false"
        - name: NEXTCLOUD_OBJECTSTORE_REGION
          value: us-east-1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 25m
            memory: "512Mi"
