apiVersion: v2
name: penpot
description: Penpot Custom Chart
type: application
version: 0.1.0
appVersion: "2.12.1"

dependencies:
  - name: penpot
    version: 0.32.0
    repository: https://helm.penpot.app
