apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: actions
spec:
  selector:
    matchLabels:
      app: k8s-runners
      app.kubernetes.io/name: k8s-runners
  template:
    metadata:
      labels:
        app: k8s-runners
        app.kubernetes.io/name: k8s-runners
    spec:
      organization: citocafecito-homelab
      labels: []
      env: []
      dockerEnabled: false
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
