apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: k8s-runner
  namespace: actions
spec:
  image: ghcr.io/actions/actions-runner:latest
  ephemeral: false
  organization: citocafecito-homelab
  env: []
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
