apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app: vault
        app.kubernetes.io/name: vault
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:latest
        command: [ "/bin/sh", "-c", "/vault/scripts/vault-entrypoint.sh" ]
        env:
        - name: SKIP_CHOWN
          value: "true"
        - name: VAULT_ADDR
          value: http://0.0.0.0:8200
        envFrom:
        - secretRef:
            name: vault-bootstrap
        ports:
        - containerPort: 8200
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /vault/config
          readOnly: true
        - name: data
          mountPath: /vault/data
        - name: vault-scripts
          mountPath: /vault/scripts
        resources:
          requests:
            memory: 128Mi
            cpu: 5m
      volumes:
      - name: config
        configMap:
          name: vault-config
          items:
          - key: vault.hcl
            path: vault.hcl
      - name: data
        hostPath:
          path: /mnt/vault/data
          type: DirectoryOrCreate
      - name: secrets
        hostPath:
          path: /mnt/vault/secrets
          type: DirectoryOrCreate
      - name: vault-scripts
        configMap:
          name: vault-entrypoint
          defaultMode: 493
