apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      app.kubernetes.io/name: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
        app.kubernetes.io/name: pihole
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-secret-admin_password: "secret/data/pihole"
        vault.hashicorp.com/agent-inject-template-admin_password: |
          {{- with secret "secret/data/pihole" -}}
          {{ .Data.data.ADMIN_PASSWORD }}
          {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
      - name: pihole
        image: pihole/pihole:2025.11.0
        env:
        - name: DNSMASQ_LISTENING
          value: all
        - name: FTLCONF_misc_etc_dnsmasq_d
          value: "true"
        - name: TZ
          value: "America/Bogota"
        - name: FTLCONF_dns_revServers
          value: 'true,192.168.1.0/16,192.168.1.1'
        - name: FTLCONF_dns_upstreams
          value: '1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4'
        - name: WEBPASSWORD_FILE
          value: "/vault/secrets/admin_password"
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: dhcp
          containerPort: 67
          protocol: UDP
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          capabilities:
            add:
            - CHOWN
            - NET_ADMIN
            - NET_BIND_SERVICE
            - NET_RAW
            - SYS_NICE
            - SYS_TIME
        volumeMounts:
        - name: pihole-etc
          mountPath: /etc/pihole
        - name: custom-dns
          mountPath: /etc/dnsmasq.d/custom.conf
          subPath: custom.conf
        - name: pihole-local-override
          mountPath: /etc/dnsmasq.d/custom-override.conf
          subPath: custom-override.conf
        - name: adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: pihole-etc
        persistentVolumeClaim:
          claimName: pihole-pvc
      - name: custom-dns
        configMap:
          name: pihole-custom-dns
      - name: pihole-local-override
        configMap:
          name: pihole-local-override
      - name: adlists
        configMap:
          name: pihole-adlists
