apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streaming
  namespace: streaming
spec:
  rules:
    - host: prowlarr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696
    - host: bazarr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767
    - host: sonarr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
    - host: radarr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
    - host: lidarr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: 8686
    - host: flaresolverr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flaresolverr
                port:
                  number: 8191
    - host: tinymediamanager.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tinymediamanager
                port:
                  number: 4000
    - host: dispatcharr.catuai.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dispatcharr
                port:
                  number: 9191