apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

resources:
- config.yaml
- transmission.yaml
- qbittorrent.yaml
- flaresolverr.yaml
- prowlarr.yaml
- sonarr.yaml
- radarr.yaml
- bazarr.yaml
- jellyserr.yaml
- jellyfin.yaml
