apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  labels:
    app: tdarr
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/part-of: streaming-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr
  template:
    metadata:
      labels:
        app: tdarr
        app.kubernetes.io/name: tdarr
        app.kubernetes.io/part-of: streaming-stack
    spec:
      containers:
      - name: tdarr
        image: ghcr.io/haveagitgat/tdarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8265
          name: web
        envFrom:
        - configMapRef:
            name: streaming-stack-config
        env:
        - name: internalNode
          value: "true"
        - name: nodeName
          value: "Tdarr-Server"
        volumeMounts:
        - name: media
          mountPath: /media
        - name: config
          mountPath: /app/configs
        - name: server
          mountPath: /app/server
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 0.2
            memory: 1Gi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: media
        hostPath:
          path: /mnt/multimedia2
          type: Directory
      - name: config
        hostPath:
          path: /mnt/tdarr/config
          type: DirectoryOrCreate
      - name: server
        hostPath:
          path: /mnt/tdarr/server
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.37
  selector:
    app: tdarr
  ports:
  - name: web
    port: 80
    targetPort: 8265
    protocol: TCP
