apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: penpot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: penpot
            port:
              number: 8080
