apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter
  labels:
    app.kubernetes.io/name: matter
    app.kubernetes.io/part-of: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter
      app.kubernetes.io/name: matter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matter
        app.kubernetes.io/name: matter
        app.kubernetes.io/part-of: home-assistant
    spec:
      hostNetwork: true
      hostIPC: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: matter
        image: ghcr.io/matter-js/python-matter-server:stable
        imagePullPolicy: IfNotPresent
        args:
        - --storage-path=/data
        - --paa-root-cert-dir=/data/credentials
        - --bluetooth-adapter=0
        - --primary-interface=enp1s0
        - --port=5582
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: CHIP_DEVICE_CONFIG_WIFI_IFACE
          value: "enp1s0" 
        - name: CHIP_MDNS_INTERFACE
          value: "enp1s0"
        ports:
        - containerPort: 5582
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /
            port: 5582
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - NET_BROADCAST
            - NET_BIND_SERVICE
            - SYS_ADMIN
        volumeMounts:
        - name: matter-config
          mountPath: /data
        - name: dbus-socket
          mountPath: /run/dbus
        - name: sysfs
          mountPath: /sys
        - name: bluetooth-dev
          mountPath: /dev/bus/usb
      volumes:
      - name: matter-config
        persistentVolumeClaim:
          claimName: matter-pvc
      - name: dbus-socket
        hostPath:
          path: /run/dbus
          type: Directory
      - name: sysfs
        hostPath:
          path: /sys
      - name: bluetooth-dev
        hostPath:
          path: /dev/bus/usb
          type: DirectoryOrCreate
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: matter
  labels:
    app.kubernetes.io/name: matter
    app.kubernetes.io/part-of: home-assistant
spec:
  selector:
    app: matter
  ports:
  - port: 5582
    targetPort: 5582
    protocol: TCP
    name: http
