apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-stack
      app.kubernetes.io/name: matter-stack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matter-stack
        app.kubernetes.io/name: matter-stack
    spec:
      containers:
      - name: bluez
        image: ghcr.io/mysticrenji/bluez-service:latest
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-bluetooth
          mountPath: /dev
        - name: dbus-socket
          mountPath: /var/run/dbus
          readOnly: true

      - name: matter-server
        image: ghcr.io/matter-js/python-matter-server:stable
        imagePullPolicy: IfNotPresent
        args:
        - --storage-path=/data
        - --paa-root-cert-dir=/data/credentials
        - --bluetooth-adapter=0
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "debug"
        ports:
        - containerPort: 5580
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 5580
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - CAP_NET_RAW
            - SYS_ADMIN
            - NET_ADMIN
          appArmorProfile:
            type: Unconfined
        volumeMounts:
        - name: matter-config
          mountPath: /data
        - name: dbus-socket
          mountPath: /var/run/dbus
          readOnly: true
        - name: dev-bluetooth
          mountPath: /dev
      dnsPolicy: Default
      hostNetwork: true
      shareProcessNamespace: true
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: matter-config
        persistentVolumeClaim:
          claimName: matter-pvc
      - name: dev-bluetooth
        hostPath:
          path: /dev
          type: Directory
      - name: dbus-socket
        hostPath:
          path: /var/run/dbus
          type: Directory
