apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
  - name: http
    protocol: TCP
    port: 8123
    targetPort: 8123
    nodePort: 30123
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-extensions
spec:
  selector:
    app: home-assistant-extensions
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
  - name: ws
    protocol: TCP
    port: 5580 # Matter Server Port
    targetPort: 5580
---
apiVersion: v1
kind: Service
metadata:
  name: matter-stack
spec:
  selector:
    app: matter-stack
  ports:
  - name: ws
    protocol: TCP
    port: 5580
    targetPort: 5580
