apiVersion: v1
kind: ConfigMap
metadata:
  name: otbr-env
data:
  OT_RCP_DEVICE: "spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=115200"
  OT_INFRA_IF: "enp1s0"
  OT_THREAD_IF: "wpan0"
  OT_LOG_LEVEL: "7"
  OT_REST_LISTEN_ADDR: "0.0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openthread
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openthread
      app.kubernetes.io/name: openthread
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openthread
        app.kubernetes.io/name: openthread
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      containers:
      - name: otbr
        image: openthread/border-router:latest
        envFrom:
        - configMapRef:
            name: otbr-env
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_RAWIO
        volumeMounts:
        - name: otbr-data
          mountPath: /data
        - name: rcp
          mountPath: /dev/ttyUSB0
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: otbr-data
        hostPath:
          path: /mnt/openthread
          type: DirectoryOrCreate
      - name: rcp
        hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: openthread
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openthread
  ports:
  - name: api
    port: 8081
    targetPort: 8081
  - name: http
    port: 5580
    targetPort: 5580
