apiVersion: v1
kind: ConfigMap
metadata:
  name: otbr-env
data:
  THREAD_BORDER_AGENT_URL: "ws://openthread.core.svc.cluster.local:8080"
  OT_RCP_DEVICE: "spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=115200"
  OT_INFRA_IF: "enp1s0"
  OT_THREAD_IF: "wpan0"
  OT_LOG_LEVEL: "7"
  OT_REST_LISTEN_ADDR: "0.0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openthread
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openthread
      app.kubernetes.io/name: openthread
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openthread
        app.kubernetes.io/name: openthread
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      containers:
      - name: otbr
        image: openthread/border-router:latest
        envFrom:
        - configMapRef:
            name: otbr-env
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: serial-device
          mountPath: /dev/ttyUSB0
          readOnly: false
        - name: otbr-data
          mountPath: /data
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: serial-device
        hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
      - name: otbr-data
        hostPath:
          path: /mnt/openthread
          type: DirectoryOrCreate
---


# apiVersion: v1
# kind: Service
# metadata:
#   name: openthread
#   labels:
#     app: openthread
# spec:
#   type: NodePort
#   selector:
#     app: openthread
#   ports:
#   - name: border-agent
#     port: 5580
#     targetPort: 5580
#   - name: rest
#     port: 8081
#     targetPort: 8081
