apiVersion: v1
kind: PersistentVolume
metadata:
  name: whisper-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/whisper
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
      app.kubernetes.io/name: whisper
  template:
    metadata:
      labels:
        app: whisper
        app.kubernetes.io/name: whisper
    spec:
      containers:
      - name: whisper
        image: rhasspy/wyoming-whisper:latest
        args:
        - "--model"
        # - "medium-int8"
        - "base-int8"
        - "--uri"
        - "tcp://0.0.0.0:9000"
        - "--data-dir"
        - "/data"
        - "--language"
        - "es"
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 5m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 2Gi
        volumeMounts:
        - name: whisper-data
          mountPath: /data
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: whisper-data
        persistentVolumeClaim:
          claimName: whisper-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
spec:
  selector:
    app: whisper
  ports:
  - name: wyoming
    port: 9000
    targetPort: 9000
    protocol: TCP
