apiVersion: v2
name: github-runners
description: GitHub Actions Runner Controller
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: actions-runner-controller
    version: 0.23.7
    repository: https://actions-runner-controller.github.io/actions-runner-controller
