apiVersion: v1
kind: ConfigMap
metadata:
  name: suwayomi-config
  namespace: media
data:
  TZ: America/Bogota
  BIND_ADDRESS: 0.0.0.0
  AUTH_MODE: BASIC_AUTH
  DATABASE_TYPE: POSTGRESQL
  DATABASE_NAME: "suwayomi"
  DATABASE_URL: "postgresql://suwayomi-postgresql.media.svc.cluster.local:5432/suwayomi"
  DATABASE_USERNAME: "suwayomi"
  DATABASE_PASSWORD: "2K<GbzK[%96p;v%O"
  EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
