apiVersion: v1
kind: Service
metadata:
  name: suwayomi-postgresql
  labels:
    app.kubernetes.io/name: suwayomi-postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: suwayomi-postgresql
