apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: suwayomi-postgresql
spec:
  serviceName: suwayomi-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: suwayomi-postgresql
      app.kubernetes.io/name: suwayomi-postgresql
  template:
    metadata:
      labels:
        app: suwayomi-postgresql
        app.kubernetes.io/name: suwayomi-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: suwayomi-config
              key: DATABASE_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: suwayomi-config
              key: DATABASE_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: suwayomi-config
              key: DATABASE_PASSWORD
        volumeMounts:
        - name: suwayomi-postgresql-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command: [ "pg_isready", "-U", "suwayomi" ]
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command: [ "pg_isready", "-U", "suwayomi" ]
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        resources:
          requests:
            cpu: 5m
            memory: 256Mi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: suwayomi-postgresql-storage
        persistentVolumeClaim:
          claimName: suwayomi-postgresql-pvc
