apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suwayomi
      app.kubernetes.io/name: suwayomi
  template:
    metadata:
      labels:
        app: suwayomi
        app.kubernetes.io/name: suwayomi
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-suwayomi: "secret/data/suwayomi"
        vault.hashicorp.com/agent-inject-template-suwayomi: |
          {{- with secret "secret/data/suwayomi" -}}
          {{ .Data.data.USERNAME | writeToFile "/vault/secrets/AUTH_USERNAME" "vault" "vault" "0644" }}
          {{ .Data.data.PASSWORD | writeToFile "/vault/secrets/AUTH_PASSWORD" "vault" "vault" "0644" }}
          {{- end -}}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: suwayomi
        image: ghcr.io/suwayomi/suwayomi-server:v2.1.2031
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          export AUTH_USERNAME=$(cat /vault/secrets/AUTH_USERNAME)
          export AUTH_PASSWORD=$(cat /vault/secrets/AUTH_PASSWORD)

          /home/suwayomi/startup_script.sh
        ports:
        - containerPort: 4567
        - containerPort: 8181
        envFrom:
        - configMapRef:
            name: suwayomi-config
        resources:
          requests:
            cpu: 50m
            memory: 1024Mi
          limits:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: suwayomi-storage
          mountPath: /home/suwayomi/.local/share/Tachidesk
      volumes:
      - name: suwayomi-storage
        persistentVolumeClaim:
          claimName: suwayomi-pvc
