apiVersion: v1
kind: Service
metadata:
  name: suwayomi
  labels:
    app.kubernetes.io/name: suwayomi
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.23
  selector:
    app.kubernetes.io/name: suwayomi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4567
  - name: web
    protocol: TCP
    port: 8181
    targetPort: 8181
