apiVersion: v1
kind: ConfigMap
metadata:
  name: linkstack-config
data:
  TZ: "Europe/Berlin"
  HTTP_SERVER_NAME: "linkstack.lan"
  HTTPS_SERVER_NAME: "linkstack.citocafecito.work"
  SERVER_ADMIN: "catuai"
  PHP_MEMORY_LIMIT: "512M"
  UPLOAD_MAX_FILESIZE: "8M"
