apiVersion: v1
kind: Service
metadata:
  name: linkstack-mysql
  labels:
    app.kubernetes.io/name: linkstack-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: linkstack-mysql
