apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Postgresql
- database-pv.yaml
- database-deployment.yaml
- database-svc.yaml

# Redis (In progress, table in the meantime)
# - cache-deployment.yaml
# - cache-svc.yaml

# LinkStack
- server-config.yaml
- server-deployment.yaml
- server-svc.yaml
- server-hpa.yaml