apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkstack
  labels:
    app: linkstack
    app.kubernetes.io/name: linkstack
    app.kubernetes.io/part-of: linkstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkstack
      app.kubernetes.io/name: linkstack
  template:
    metadata:
      labels:
        app: linkstack
        app.kubernetes.io/name: linkstack
        app.kubernetes.io/part-of: linkstack
    spec:
      containers:
      - name: linkstack
        image: ghcr.io/linkstackorg/linkstack:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: linkstack-config
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
