apiVersion: v1
kind: Service
metadata:
  name: linkstack
  labels:
    app.kubernetes.io/name: linkstack
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.25
  selector:
    app.kubernetes.io/name: linkstack
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8190
      targetPort: 443
