apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mydrive-mongodb
spec:
  serviceName: mydrive-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mydrive-mongodb
      app.kubernetes.io/name: mydrive-mongodb
      app.kubernetes.io/part-of: mydrive
  template:
    metadata:
      labels:
        app: mydrive-mongodb
        app.kubernetes.io/name: mydrive-mongodb
        app.kubernetes.io/part-of: mydrive
    spec:
      containers:
        - name: mongo
          image: mongo:8.2.3
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
        - name: data
          hostPath:
            path: /mnt/mydrive-mongodb
            type: DirectoryOrCreate
