apiVersion: v1
kind: Service
metadata:
  name: mydrive-mongodb
  labels:
    app: mydrive-mongodb
    app.kubernetes.io/name: mydrive-mongodb
    app.kubernetes.io/part-of: mydrive
spec:
  clusterIP: None
  selector:
    app: mydrive-mongodb
    app.kubernetes.io/name: mydrive-mongodb
    app.kubernetes.io/part-of: mydrive
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017