apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Mongodb
- database-pv.yaml
- database-statefulset.yaml
- database-svc.yaml

# MyDrive
- server-deployment.yaml
- server-svc.yaml
