apiVersion: v1
kind: Service
metadata:
  name: mydrive
  labels:
    app.kubernetes.io/name: mydrive
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.32
  selector:
    app.kubernetes.io/name: mydrive
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 8080
