apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  github_app_id: {{ .Values.githubApp.id | toString | b64enc | quote }}
  github_app_installation_id: {{ .Values.githubApp.installationId | toString | b64enc | quote }}
  github_app_private_key: {{ .Values.githubApp.privateKey | b64enc | quote }}