apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glances
spec:
  selector:
    matchLabels:
      app: glances
      app.kubernetes.io/name: glances
  template:
    metadata:
      labels:
        app: glances
        app.kubernetes.io/name: glances
    spec:
      hostPID: true
      containers:
        - name: glances
          image: nicolargo/glances:latest
          env:
            - name: GLANCES_OPT
              value: "-w -B 0.0.0.0 --disable-plugin processlist --fs-free-space"
          ports:
            - containerPort: 61208
              hostPort: 61208
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
        - name: host-root
          hostPath:
            path: /
