apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: kubetail.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubetail-dashboard
            port:
              number: 8080
  - host: kite.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kite
            port:
              number: 8080