apiVersion: v2
name: cert-manager
description: cert-manager bootstrap
type: application
version: v1.14.5
appVersion: v1.14.5

dependencies:
  - name: cert-manager
    version: v1.14.5
    repository: https://charts.jetstack.io