apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-assistant-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/music-assistant
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
      app.kubernetes.io/name: music-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: music-assistant
        app.kubernetes.io/name: music-assistant
    spec:
      hostNetwork: true
      containers:
      - name: music-assistant
        image: ghcr.io/music-assistant/server:latest
        ports:
        - name: tcp
          protocol: TCP
          containerPort: 8095
        resources:
          requests:
            cpu: 200m
            memory: 515Mi
          limits:
            cpu: 1
            memory: 1024Mi
        securityContext:
          privileged: true
          capabilities:
            add:
            - DAC_READ_SEARCH
            - SYS_ADMIN
        volumeMounts:
        - name: music-assistant-data
          mountPath: /data
      nodeSelector:
        kubernetes.io/hostname: caturra
      volumes:
      - name: music-assistant-data
        persistentVolumeClaim:
          claimName: music-assistant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-assistant
spec:
  selector:
    app: music-assistant
  ports:
  - name: http
    protocol: TCP
    port: 8095
    targetPort: 8095
