# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ring-mqtt-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: /mnt/ring-mqtt
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ring-mqtt-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ring-mqtt
  labels:
    app: ring-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ring-mqtt
      app.kubernetes.io/name: ring-mqtt
      app.kubernetes.io/part-of: home-assistant
  serviceName: ring-mqtt
  template:
    metadata:
      labels:
        app: ring-mqtt
        app.kubernetes.io/name: ring-mqtt
        app.kubernetes.io/part-of: home-assistant
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-config.json: "secret/data/ring"
        vault.hashicorp.com/agent-inject-template-config.json: |
          {{- with secret "secret/data/ring" -}}
          {
            "mqtt_url": "mqtt://mosquitto:1883",
            "mqtt_user": "",
            "mqtt_pass": "",
            "ring_username": "{{ .Data.data.USERNAME }}",
            "ring_password": "{{ .Data.data.PASSWORD }}",
            "enable_modes": false,
            "discovery": true,
            "log_level": "info",
            "livestream_user": "{{ .Data.data.CAMERA_USERNAME }}",
            "livestream_pass": "{{ .Data.data.CAMERA_PASSWORD }}",
            "enable_cameras": true,
            "mqtt_client_id": "ring-mqtt"
          }
          {{- end }}
    spec:
      containers:
      - name: ring-mqtt
        image: tsightler/ring-mqtt:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c" ]
        args:
        - cp /vault/secrets/config.json /data/config.json && /init
        ports:
        - containerPort: 51824
          name: web-ui
        - containerPort: 55123
          name: auth-ui
        - containerPort: 8554
          name: rtsp
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: ring-data
          mountPath: /data
      volumes:
      - name: ring-data
        hostPath:
          path: /mnt/ring-mqtt
          type: DirectoryOrCreate
---
apiVersion: v1 
kind: Service
metadata:
  name: ring-mqtt
spec:
  selector:
    app: ring-mqtt
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 51824
    targetPort: 51824
    name: web-ui
  - protocol: TCP
    port: 55123
    targetPort: 55123
    name: auth-ui
  - protocol: TCP
    port: 8554
    targetPort: 8554
    name: rtsp
---
apiVersion: v1
kind: Service
metadata:
  name: ring-mqtt-local
spec:
  selector:
    app: ring-mqtt
  type: NodePort
  ports:
  - protocol: TCP
    port: 55123 # El puerto interno real del contenedor
    targetPort: 55123 # Puerto expuesto por Ring-MQTT
    nodePort: 31824 # El puerto accesible desde tu red (puedes mantenerlo)
    name: web-ui
