apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/zigbee2mqtt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
      app.kubernetes.io/name: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      restartPolicy: Always
      containers:
      - name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt:latest
        env:
        - name: TZ
          value: "America/Bogota"
        - name: ZIGBEE2MQTT_DATA
          value: /app/data
        - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
          value: "zigbee2mqtt"
        - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
          value: "mqtt://mosquitto:1883"
        - name: ZIGBEE2MQTT_MQTT_RECONNECT_PERIOD
          value: "5000"
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
          value: /dev/ttyUSB0
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
          value: zstack
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE
          value: "460800"
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 5m
            memory: 256Mi
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_RAWIO
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: devices
          mountPath: /dev/ttyUSB0
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-pvc
      - name: config
        configMap:
          name: zigbee2mqtt-config
      - name: devices
        hostPath:
          path: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
spec:
  selector:
    app: zigbee2mqtt
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30088
