---
apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-tracker-configmap
data:
  PUID: "1000"
  PGID: "1000"
  DB_CONNECTION: "sqlite"
  SPEEDTEST_SCHEDULE: "0 */12 * * *"
  APP_TIMEZONE: "America/Bogota"
  FILE__ADMIN_EMAIL: /vault/secrets/admin_email
  FILE__ADMIN_NAME: /vault/secrets/admin_name
  FILE__ADMIN_PASSWORD: /vault/secrets/admin_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
      app.kubernetes.io/name: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
        app.kubernetes.io/name: speedtest-tracker
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-speedtest: "secret/data/speedtest"
        vault.hashicorp.com/agent-inject-template-speedtest: |
          {{- with secret "secret/data/speedtest " -}}
          ADMIN_EMAIL="{{ .Data.data.ADMIN_EMAIL }}"
          ADMIN_NAME="{{ .Data.data.ADMIN_NAME }}"
          ADMIN_PASSWORD="{{ .Data.data.ADMIN_PASSWORD }}"
          {{ .Data.data.ADMIN_EMAIL | writeToFile "/vault/secrets/admin_email" "vault" "vault" "0600" }}
          {{ .Data.data.ADMIN_NAME | writeToFile "/vault/secrets/admin_name" "vault" "vault" "0600" }}
          {{ .Data.data.ADMIN_PASSWORD | writeToFile "/vault/secrets/admin_password" "vault" "vault" "0600" }}
          {{- end -}}
    spec:
      containers:
      - name: speedtest-tracker
        image: lscr.io/linuxserver/speedtest-tracker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: speedtest
              key: APP_KEY
        envFrom:
        - configMapRef:
            name: speedtest-tracker-configmap
        volumeMounts:
        - name: speedtest-tracker-storage
          mountPath: /config
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: speedtest-tracker-storage
        hostPath:
          path: /mnt/speedtest-tracker
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
spec:
  selector:
    app: speedtest-tracker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
spec:
  type: NodePort
  selector:
    app: speedtest-tracker
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30880
