apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wikijs-postgresql
spec:
  serviceName: wikijs-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: wikijs-postgresql
      app.kubernetes.io/name: wikijs-postgresql
  template:
    metadata:
      labels:
        app: wikijs-postgresql
        app.kubernetes.io/name: wikijs-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: wikijs-database
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: wikijs-database
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: wikijs-database
              key: DB_PASSWORD
        volumeMounts:
        - name: wikijs-postgresql-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command: [ "pg_isready", "-U", "wikijs" ]
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command: [ "pg_isready", "-U", "wikijs" ]
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        resources:
          requests:
            cpu: 5m
            memory: 256Mi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: wikijs-postgresql-storage
        persistentVolumeClaim:
          claimName: wikijs-postgresql-pvc
