apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    app.kubernetes.io/name: wikijs
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.231
  selector:
    app.kubernetes.io/name: wikijs
  ports:
  - name: http
    port: 80
    targetPort: 3000
